### ISSUE TITLE
error: unrecognized arguments: 300 300 --custom_func_dir .

### ISSUE THREAD

**Issue by zifengdexiatian** [JLans/vp_model#1]
I encountered an error running the example in the readme,It looks like the parameters won't parse, I don't know how to modify the parameters to make them work correctly, or there's something wrong with the example.I use a linux system.
![image](https://github.com/JLans/vp_model/assets/83349433/282cdb77-65e2-4839-8bc3-f74646af7f91)

**Comment by zifengdexiatian** [comment]
I modified the training parameter list and now it works, but I'm not sure if this modification fits the example in the author's article.
![image](https://github.com/JLans/vp_model/assets/83349433/706f3c54-61b3-4b7e-9f45-85e5dc166f21)

**Comment by JLans** [comment]
I am still working on merging my chemprop fork with the main branch. In the mean time, the vp_model package requires the chemprop available here: https://github.com/JLans/chemprop. The necessary chemprop package can be obtained via the command "git clone --branch transfer_learning https://github.com/JLans/chemprop.git".

**Comment by zifengdexiatian** [comment]
Thank you, when I use "pip install chemprop" installation chemprop come from https://github.com/chemprop/chemprop. I according to provide you "git clone - branch transfer_learning https://github.com/JLans/chemprop.git" installed chemprop again, now the error disappeared.
